import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  CalendarDays,
  ContactRound,
  MessageSquareText,
  Network,
  Sparkles,
  UserRoundPlus,
} from "lucide-react";

export type Locale = "en" | "zh" | "ja";
export type Theme = "dark" | "light";
export type SectionId = "ai" | "events" | "people" | "connections" | "analytics";
export type AiResultMode = "idle" | "events" | "people" | "analytics";

export type NavItem = {
  id: SectionId;
  icon: LucideIcon;
};

export const navItems: NavItem[] = [
  { id: "ai", icon: Sparkles },
  { id: "events", icon: CalendarDays },
  { id: "people", icon: UserRoundPlus },
  { id: "connections", icon: ContactRound },
  { id: "analytics", icon: BarChart3 },
];

export const localeMeta = {
  en: { label: "English", htmlLang: "en" },
  zh: { label: "中文", htmlLang: "zh-CN" },
  ja: { label: "日本語", htmlLang: "ja" },
} satisfies Record<Locale, { label: string; htmlLang: string }>;

export const copy = {
  en: {
    brand: "Orbit Control",
    tagline: "AI-Augmented Network Command",
    commandCenter: "Command Center",
    version: "v2.4.0",
    themeDark: "Dark",
    themeBright: "Bright",
    settings: "Settings",
    support: "Support",
    notifications: "Notifications",
    automation: "Automation",
    globalSearch: "Search orbit...",
    nav: {
      ai: "Orbit AI",
      events: "Events",
      people: "People",
      connections: "Connections",
      analytics: "Analytics",
    },
    aiChat: {
      title: "Ask Orbit AI",
      context: "Orbit AI Context",
      userPrompt: "What are you trying to achieve in Tokyo?",
      assistantIdle:
        "Tell me what kind of opportunity you want: an event to attend, people to meet, or the state of your network. I will open the evidence panel when there is something useful to show.",
      resultIdle: "Ask for events, people, or network analysis to open a live panel here.",
      recommendEvents: "Recommend events",
      recommendPeople: "Recommend people",
      analyzeNetwork: "Analyze network",
      inputPlaceholder: "Ask Orbit...",
      resultsTitle: "Context panel",
      eventsTitle: "Recommended Events",
      eventsSubtitle: "Curated based on your strategic networking goals.",
      eventsAnswer:
        "I found 3 high-signal events based on your AI infrastructure focus and your goal to connect with Series A founders.",
      peopleTitle: "People Recommendations",
      peopleSubtitle: "Ranked by business fit and shared goals across your network.",
      peopleAnswer:
        "I ranked people by business fit, shared event context, and likelihood of a useful conversation based on recent activity.",
      analyticsTitle: "Network Signal",
      analyticsAnswer:
        "Your orbit is strong in AI infrastructure and under-indexed in Fintech. I would prioritize two founder events and one targeted intro.",
      orbitTitle: "Live relationship orbit",
      resultsPanelLabel: "AI results panel",
      sendCommand: "Send command",
      centerAvatarAlt: "Executive user at orbit center",
      matchLabel: "Match",
      fitLabel: "Fit",
      whyEvent: "Why this matches you:",
      whyEventBody: "target attendees overlap with your current network goals.",
      whyPeople: "Why this matches",
      viewDetails: "View Details",
      saveToCardHolder: "Save to Card Holder",
      requestIntro: "Request Intro",
    },
    heroKicker: "Tokyo hub active",
    heroTitle: "Find your orbit in Tokyo.",
    heroBody:
      "Orbit helps you find the right event, meet the right people, and keep the relationship moving. Command your network.",
    aiPlaceholder: "What are you looking to achieve today?",
    suggestedCommands: "Suggested commands",
    commands: ["Find a high-fit AI event", "Who should I meet next?", "Draft follow-ups"],
    liveActivity: "Live Network Activity",
    nodesConnected: "142 nodes connected",
    modeCards: [
      {
        title: "Before: Discover",
        body: "AI curates events matching your goals, seniority, and technical stack.",
      },
      {
        title: "During: Connect",
        body: "Real-time contextual briefings reveal who is in the room and why they matter.",
      },
      {
        title: "After: Follow-up",
        body: "Smart card exchange tracking and AI-drafted prompts keep momentum alive.",
      },
    ],
    recommended: "Recommended for You",
    recommendedSub: "High-match events and people in your vicinity",
    requestAccess: "Request Access",
    register: "Register",
    join: "Join",
    message: "Message",
    profile: "Profile",
    viewAll: "View all",
    eventHub: "Events Hub",
    peopleHub: "People Hub",
    connectionHub: "Card Holder",
    analyticsHub: "Network Analytics",
    eventIntro: "Global industry gatherings curated for your growth trajectory.",
    peopleIntro: "Strategically manage professional relationships and network capital.",
    connectionIntro: "Manage your professional network through AI-augmented digital card insights.",
    analyticsIntro: "Real-time telemetry on connection density and value.",
    exportCrm: "Export CRM",
    addConnection: "Add Connection",
    scanCard: "Scan New Card",
    exportReport: "Export Report",
    last30Days: "Last 30 Days",
    ai: {
      title: "Orbit AI",
      subtitle: "Contextual Intelligence",
      leads: "High-value unsaved leads",
      actions: "Suggested actions",
      inputTitle: "Ask AI Assistant...",
      inputPlaceholder: "Type a command...",
      draftEmail: "Draft Email",
      connect: "Connect",
    },
    stats: [
      ["Network Value Index", "84.2", "+3.4%"],
      ["Active Nodes", "1,248", "+12"],
      ["Growth Velocity", "4.2x", "+0.8"],
      ["Avg Resonance", "High", "75%"],
    ],
    tabs: {
      recent: "Recent",
      highValue: "High Value",
      followUp: "Needs Follow-up",
      allCards: "All Cards",
      recentScans: "Recent Scans",
      favorites: "Favorites",
    },
    ui: {
      orbitWorkflow: "Orbit workflow",
      calendarView: "Calendar View",
      hostEvent: "Host Event",
      otherAvailableEvents: "Other Available Events",
      eventSearchPlaceholder: "Search keywords, industry, people",
      allLocations: "All Locations",
      industry: "Industry",
      anyDate: "Any Date",
      match: "Match",
      resonance: "Resonance",
      sendNote: "Send Note",
      calendar: "Calendar",
      more: "More",
      viewInsights: "View Insights",
      importFromLinkedIn: "Import from LinkedIn",
      addNetwork: "Add Network",
      followUpSana: "Follow up with Sana",
      followUpSanaBody: "Met at Tokyo AI Summit. Discussed Series B roadmap.",
      inviteMarcus: "Invite Marcus to LinkedIn",
      inviteMarcusBody: "You share 14 mutual connections in Fintech.",
      networkGrowthTrajectory: "Network Growth Trajectory",
      resonanceDistribution: "Resonance Distribution",
      highSignal: "High Signal",
      nurture: "Nurture",
      dormant: "Dormant",
      resonanceSummary: "Your network is highly active. High Signal connections have increased by 5% this quarter.",
      catalystEvents: "High-Signal Catalyst Events",
      strategicInsights: "Strategic Insights",
      networkGapAnalysis: "Network Gap Analysis",
      networkGapBody: "You are under-indexed in Fintech relative to stated goals. Consider attending Fin-Forward.",
      nurtureReminder: "Nurture Reminder",
      nurtureBody: "3 high-resonance contacts have not been engaged in 30 days. Initiating follow-up sequence is recommended.",
      networkExpansion: "Network Expansion",
      networkExpansionBody: "Velocity and reach over the last 30 days.",
      newScans: "New scans",
      interactions: "Interactions",
      topGroups: "Top Groups",
      cards: "cards",
      manageGroups: "Manage Groups",
    },
  },
  zh: {
    brand: "Orbit Control",
    tagline: "AI 增强网络指挥中心",
    commandCenter: "指挥中心",
    version: "v2.4.0",
    themeDark: "深色",
    themeBright: "明亮",
    settings: "设置",
    support: "支持",
    notifications: "通知",
    automation: "自动化",
    globalSearch: "搜索 Orbit...",
    nav: {
      ai: "Orbit AI",
      events: "活动",
      people: "人脉",
      connections: "名片夹",
      analytics: "分析",
    },
    aiChat: {
      title: "询问 Orbit AI",
      context: "Orbit AI 上下文",
      userPrompt: "你想在东京达成什么？",
      assistantIdle: "告诉我你想找活动、想认识的人，或者想查看网络状态。有可展示的信息时，我会在右侧打开证据面板。",
      resultIdle: "询问活动、人脉或网络分析后，这里会打开实时面板。",
      recommendEvents: "推荐活动",
      recommendPeople: "推荐人脉",
      analyzeNetwork: "分析网络",
      inputPlaceholder: "询问 Orbit...",
      resultsTitle: "上下文面板",
      eventsTitle: "推荐活动",
      eventsSubtitle: "根据你的战略社交目标精选。",
      eventsAnswer: "我根据你的 AI 基础设施关注点，以及连接 Series A 创始人的目标，找到了 3 个高信号活动。",
      peopleTitle: "人脉推荐",
      peopleSubtitle: "按业务匹配度和网络中的共同目标排序。",
      peopleAnswer: "我按业务匹配度、共同活动上下文和近期活跃度，排序了最可能产生有效对话的人。",
      analyticsTitle: "网络信号",
      analyticsAnswer: "你的 AI 基础设施轨道很强，但 Fintech 偏弱。建议优先两个创始人活动和一次精准介绍。",
      orbitTitle: "实时关系轨道",
      resultsPanelLabel: "AI 结果面板",
      sendCommand: "发送指令",
      centerAvatarAlt: "轨道中心的用户头像",
      matchLabel: "匹配",
      fitLabel: "适配",
      whyEvent: "为什么匹配你：",
      whyEventBody: "目标参会者与你当前的网络目标高度重合。",
      whyPeople: "为什么匹配",
      viewDetails: "查看详情",
      saveToCardHolder: "保存到名片夹",
      requestIntro: "请求介绍",
    },
    heroKicker: "东京枢纽已激活",
    heroTitle: "在东京找到你的轨道。",
    heroBody: "Orbit 帮你找到合适活动、遇见合适的人，并持续推进关系。掌控你的网络。",
    aiPlaceholder: "今天想达成什么？",
    suggestedCommands: "建议指令",
    commands: ["帮我找一个高匹配 AI 活动", "下一位该见谁？", "起草跟进信息"],
    liveActivity: "实时网络活动",
    nodesConnected: "142 个节点已连接",
    modeCards: [
      { title: "之前：发现", body: "AI 根据你的目标、资历和技术栈筛选活动。" },
      { title: "期间：连接", body: "实时上下文简报说明谁在现场，以及为什么值得认识。" },
      { title: "之后：跟进", body: "智能名片交换记录和 AI 草稿让关系保持推进。" },
    ],
    recommended: "为你推荐",
    recommendedSub: "你附近的高匹配活动与人脉",
    requestAccess: "请求加入",
    register: "报名",
    join: "加入",
    message: "发消息",
    profile: "资料",
    viewAll: "查看全部",
    eventHub: "活动中心",
    peopleHub: "人脉中心",
    connectionHub: "名片夹",
    analyticsHub: "网络分析",
    eventIntro: "为你的成长路径精选全球行业活动。",
    peopleIntro: "战略化管理你的专业关系与网络资本。",
    connectionIntro: "通过 AI 增强的数字名片洞察管理专业网络。",
    analyticsIntro: "实时呈现连接密度与关系价值。",
    exportCrm: "导出 CRM",
    addConnection: "添加联系人",
    scanCard: "扫描新名片",
    exportReport: "导出报告",
    last30Days: "最近 30 天",
    ai: {
      title: "Orbit AI",
      subtitle: "上下文智能",
      leads: "高价值未保存联系人",
      actions: "建议动作",
      inputTitle: "询问 AI 助手...",
      inputPlaceholder: "输入指令...",
      draftEmail: "起草邮件",
      connect: "连接",
    },
    stats: [
      ["网络价值指数", "84.2", "+3.4%"],
      ["活跃节点", "1,248", "+12"],
      ["增长速度", "4.2x", "+0.8"],
      ["平均共振", "高", "75%"],
    ],
    tabs: {
      recent: "最近",
      highValue: "高价值",
      followUp: "需要跟进",
      allCards: "全部名片",
      recentScans: "最近扫描",
      favorites: "收藏",
    },
    ui: {
      orbitWorkflow: "Orbit 工作流",
      calendarView: "日历视图",
      hostEvent: "发布活动",
      otherAvailableEvents: "其他可参加活动",
      eventSearchPlaceholder: "搜索关键词、行业或人脉",
      allLocations: "全部地点",
      industry: "行业",
      anyDate: "任意日期",
      match: "匹配",
      resonance: "共振",
      sendNote: "发送备注",
      calendar: "日历",
      more: "更多",
      viewInsights: "查看洞察",
      importFromLinkedIn: "从 LinkedIn 导入",
      addNetwork: "加入网络",
      followUpSana: "跟进 Sana",
      followUpSanaBody: "在 Tokyo AI Summit 见过，讨论过 Series B 路线图。",
      inviteMarcus: "邀请 Marcus 到 LinkedIn",
      inviteMarcusBody: "你们在 Fintech 领域有 14 个共同联系人。",
      networkGrowthTrajectory: "网络增长轨迹",
      resonanceDistribution: "共振分布",
      highSignal: "高信号",
      nurture: "培养中",
      dormant: "沉睡",
      resonanceSummary: "你的网络活跃度很高。本季度高信号联系人增加了 5%。",
      catalystEvents: "高信号催化活动",
      strategicInsights: "战略洞察",
      networkGapAnalysis: "网络缺口分析",
      networkGapBody: "相对你设定的目标，Fintech 人脉偏弱。建议参加 Fin-Forward。",
      nurtureReminder: "培养提醒",
      nurtureBody: "3 位高共振联系人已有 30 天未互动，建议启动跟进序列。",
      networkExpansion: "网络扩展",
      networkExpansionBody: "最近 30 天的增长速度和覆盖范围。",
      newScans: "新增扫描",
      interactions: "互动",
      topGroups: "重点群组",
      cards: "张名片",
      manageGroups: "管理群组",
    },
  },
  ja: {
    brand: "Orbit Control",
    tagline: "AI 拡張ネットワーク司令室",
    commandCenter: "コマンドセンター",
    version: "v2.4.0",
    themeDark: "ダーク",
    themeBright: "ブライト",
    settings: "設定",
    support: "サポート",
    notifications: "通知",
    automation: "自動化",
    globalSearch: "Orbit を検索...",
    nav: {
      ai: "Orbit AI",
      events: "イベント",
      people: "人脈",
      connections: "カードホルダー",
      analytics: "分析",
    },
    aiChat: {
      title: "Orbit AI に聞く",
      context: "Orbit AI コンテキスト",
      userPrompt: "東京で何を達成したいですか？",
      assistantIdle:
        "参加したいイベント、会うべき人、ネットワークの状態を教えてください。表示できる根拠があれば右側のパネルを開きます。",
      resultIdle: "イベント、人脈、ネットワーク分析を聞くと、ここにライブパネルが開きます。",
      recommendEvents: "イベントを推薦",
      recommendPeople: "人脈を推薦",
      analyzeNetwork: "ネットワーク分析",
      inputPlaceholder: "Orbit に聞く...",
      resultsTitle: "コンテキストパネル",
      eventsTitle: "おすすめイベント",
      eventsSubtitle: "戦略的なネットワーキング目標に基づいて選定。",
      eventsAnswer:
        "AI インフラへの関心と Series A 創業者につながる目標をもとに、シグナルの高いイベントを 3 件見つけました。",
      peopleTitle: "人脈レコメンド",
      peopleSubtitle: "ビジネス適合度とネットワーク内の共通目標でランク付け。",
      peopleAnswer:
        "ビジネス適合度、共有イベント文脈、直近の活動から有益な会話につながる人物をランク付けしました。",
      analyticsTitle: "ネットワークシグナル",
      analyticsAnswer:
        "AI インフラの軌道は強い一方で Fintech が弱めです。創業者イベント 2 件と精度の高い紹介 1 件を優先しましょう。",
      orbitTitle: "ライブ関係軌道",
      resultsPanelLabel: "AI 結果パネル",
      sendCommand: "コマンドを送信",
      centerAvatarAlt: "軌道中心のユーザーアバター",
      matchLabel: "一致",
      fitLabel: "適合",
      whyEvent: "一致する理由：",
      whyEventBody: "対象参加者が現在のネットワーク目標と重なっています。",
      whyPeople: "一致する理由",
      viewDetails: "詳細を見る",
      saveToCardHolder: "カードホルダーに保存",
      requestIntro: "紹介を依頼",
    },
    heroKicker: "東京ハブ稼働中",
    heroTitle: "東京であなたの軌道を見つける。",
    heroBody:
      "Orbit は最適なイベント、会うべき人、次のフォローアップをつなげます。あなたのネットワークを指揮しましょう。",
    aiPlaceholder: "今日は何を達成しますか？",
    suggestedCommands: "おすすめコマンド",
    commands: ["高適合の AI イベントを探す", "次に会うべき人は？", "フォローアップを作成"],
    liveActivity: "ライブネットワーク活動",
    nodesConnected: "142 ノード接続中",
    modeCards: [
      { title: "前：発見", body: "AI が目標、役職、技術スタックに合うイベントを選びます。" },
      { title: "中：接続", body: "会場にいる重要人物と、その理由をリアルタイムで把握できます。" },
      { title: "後：フォロー", body: "名刺交換の追跡と AI 下書きで関係を前に進めます。" },
    ],
    recommended: "あなたへのおすすめ",
    recommendedSub: "近くの高適合イベントと人物",
    requestAccess: "参加を申請",
    register: "登録",
    join: "参加",
    message: "メッセージ",
    profile: "プロフィール",
    viewAll: "すべて表示",
    eventHub: "イベントハブ",
    peopleHub: "人脈ハブ",
    connectionHub: "カードホルダー",
    analyticsHub: "ネットワーク分析",
    eventIntro: "成長戦略に合わせたグローバル業界イベント。",
    peopleIntro: "専門的な関係とネットワーク資本を戦略的に管理します。",
    connectionIntro: "AI 拡張デジタルカードの洞察で専門ネットワークを管理します。",
    analyticsIntro: "接続密度と価値をリアルタイムで可視化します。",
    exportCrm: "CRM 書き出し",
    addConnection: "接続を追加",
    scanCard: "新しいカードをスキャン",
    exportReport: "レポート出力",
    last30Days: "過去 30 日",
    ai: {
      title: "Orbit AI",
      subtitle: "コンテキスト知能",
      leads: "未保存の高価値リード",
      actions: "おすすめアクション",
      inputTitle: "AI アシスタントに質問...",
      inputPlaceholder: "コマンドを入力...",
      draftEmail: "メール下書き",
      connect: "接続",
    },
    stats: [
      ["ネットワーク価値指数", "84.2", "+3.4%"],
      ["アクティブノード", "1,248", "+12"],
      ["成長速度", "4.2x", "+0.8"],
      ["平均共鳴", "高", "75%"],
    ],
    tabs: {
      recent: "最近",
      highValue: "高価値",
      followUp: "要フォロー",
      allCards: "すべてのカード",
      recentScans: "最近のスキャン",
      favorites: "お気に入り",
    },
    ui: {
      orbitWorkflow: "Orbit ワークフロー",
      calendarView: "カレンダー表示",
      hostEvent: "イベントを作成",
      otherAvailableEvents: "その他の参加可能イベント",
      eventSearchPlaceholder: "キーワード、業界、人脈を検索",
      allLocations: "すべての場所",
      industry: "業界",
      anyDate: "任意の日付",
      match: "一致",
      resonance: "共鳴",
      sendNote: "メモを送信",
      calendar: "カレンダー",
      more: "その他",
      viewInsights: "インサイトを見る",
      importFromLinkedIn: "LinkedIn から取り込み",
      addNetwork: "ネットワークに追加",
      followUpSana: "Sana をフォローアップ",
      followUpSanaBody: "Tokyo AI Summit で会い、Series B のロードマップを話しました。",
      inviteMarcus: "Marcus を LinkedIn に招待",
      inviteMarcusBody: "Fintech 領域で 14 人の共通接点があります。",
      networkGrowthTrajectory: "ネットワーク成長軌跡",
      resonanceDistribution: "共鳴分布",
      highSignal: "高シグナル",
      nurture: "育成中",
      dormant: "休眠",
      resonanceSummary: "ネットワークは高い活動状態です。高シグナル接点は今四半期に 5% 増加しました。",
      catalystEvents: "高シグナル触媒イベント",
      strategicInsights: "戦略インサイト",
      networkGapAnalysis: "ネットワークギャップ分析",
      networkGapBody: "設定した目標に対して Fintech が不足しています。Fin-Forward への参加を検討してください。",
      nurtureReminder: "育成リマインダー",
      nurtureBody: "高共鳴の接点 3 名と 30 日間接触がありません。フォローアップの開始をおすすめします。",
      networkExpansion: "ネットワーク拡張",
      networkExpansionBody: "過去 30 日間の速度と到達範囲。",
      newScans: "新規スキャン",
      interactions: "インタラクション",
      topGroups: "主要グループ",
      cards: "枚のカード",
      manageGroups: "グループ管理",
    },
  },
} satisfies Record<Locale, unknown>;

export const events = [
  {
    title: "Global AI Infrastructure Summit 2024",
    category: "Technology · AI",
    meta: "Tokyo International Forum · Oct 12",
    match: "94%",
    tone: "cyan",
    image:
      "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=80",
    tags: ["Web3", "Hardware"],
  },
  {
    title: "Shibuya Deep Tech Connect",
    category: "Founder Mixer",
    meta: "Trunk Hotel · 19:00 JST",
    match: "88%",
    tone: "magenta",
    image:
      "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=900&q=80",
    tags: ["Series B", "Fintech"],
  },
  {
    title: "Orbit Security: Zero Trust 2.0",
    category: "Cybersecurity",
    meta: "Virtual Event · Oct 29",
    match: "92%",
    tone: "green",
    image:
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=80",
    tags: ["Security", "Enterprise"],
  },
];

export const people = [
  {
    name: "Elena Vost",
    role: "CTO, Neuralink",
    resonance: 94,
    status: "High Match",
    action: "Message",
    image:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=240&q=80",
  },
  {
    name: "Marcus Thorne",
    role: "Partner, Sequoia",
    resonance: 62,
    status: "Follow-up",
    action: "Send Note",
    image:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=80",
  },
  {
    name: "Sana Al-Fayed",
    role: "Principal, Ideo",
    resonance: 88,
    status: "Upcoming",
    action: "Calendar",
    image:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=240&q=80",
  },
  {
    name: "Jordan Chen",
    role: "Founder, Stealth AI",
    resonance: 75,
    status: "Introduced",
    action: "Profile",
    image:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=240&q=80",
  },
];

export const leads = [
  {
    name: "Sarah Chen",
    role: "VP Engineering @ Quantum",
    match: "98%",
    image:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=180&q=80",
  },
  {
    name: "Marcus Thorne",
    role: "Managing Partner @ Blue Ventures",
    match: "92%",
    image:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=180&q=80",
  },
];

export const peopleRecommendations = [
  {
    name: "David Lin",
    role: "CTO at Sentinel AI",
    fit: "98%",
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=220&q=80",
    reasons: [
      "Both actively looking for Series A AI infrastructure founders.",
      "Shared past experience scaling enterprise LLM deployments.",
    ],
    opener:
      "Hi David, noticed we're both focused on enterprise LLM scaling at the summit. Would love to swap notes on deployment friction.",
  },
  {
    name: "Elena Rostova",
    role: "Partner at Vertex Ventures",
    fit: "92%",
    image:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=220&q=80",
    reasons: [
      "Her fund recently opened a new deep-tech thesis covering your sector.",
      "You share 3 mutual connections from previous accelerators.",
    ],
    opener:
      "Elena, noticed Vertex's new thesis on agentic workflows. Our current architecture tackles exactly the latency issues in your recent post.",
  },
];

export const orbitContacts = [
  {
    name: "Sarah Chen",
    initials: "SC",
    orbit: 1,
    delay: "-1s",
    duration: "18s",
    image:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=160&q=80",
  },
  {
    name: "Marcus Thorne",
    initials: "MT",
    orbit: 2,
    delay: "-4s",
    duration: "26s",
    image:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=160&q=80",
  },
  {
    name: "Elena Vost",
    initials: "EV",
    orbit: 3,
    delay: "-8s",
    duration: "34s",
    image:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80",
  },
  {
    name: "Jordan Chen",
    initials: "JC",
    orbit: 1,
    delay: "-11s",
    duration: "20s",
    image:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=160&q=80",
  },
  {
    name: "Sana Al-Fayed",
    initials: "SA",
    orbit: 2,
    delay: "-14s",
    duration: "28s",
    image:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=160&q=80",
  },
  {
    name: "Priya Sharma",
    initials: "PS",
    orbit: 3,
    delay: "-18s",
    duration: "38s",
    image:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=160&q=80",
  },
];

export const catalysts = [
  ["Global Tech Summit '24", "Oct 12-14", "+45", "85%"],
  ["AI Founders Dinner", "Nov 02", "+12", "92%"],
  ["Q3 Syndicate Meetup", "Sep 28", "+28", "45%"],
];

export const orbitNodes = [
  { x: 20, y: 28, size: "lg", label: "VC" },
  { x: 42, y: 18, size: "sm", label: "AI" },
  { x: 68, y: 32, size: "md", label: "CX" },
  { x: 36, y: 58, size: "md", label: "BD" },
  { x: 76, y: 66, size: "sm", label: "SE" },
  { x: 56, y: 48, size: "lg", label: "JP" },
];

export const quickMetrics = [
  { icon: Network, value: "142", label: "nodes" },
  { icon: Sparkles, value: "18", label: "matches" },
  { icon: MessageSquareText, value: "7", label: "follow-ups" },
];
